#!/bin/bash 

#########################################################
#
# Platform: NCI Gadi HPC
# Description:  Simple check with flagstats
# see github.com/Sydney-Informatics-Hub/Fix-BAM-read-groups
#
# Author/s: Cali Willet
# cali.willet@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

### Submit via for loop - 
# samples=($(awk -F "," '{print $1}' Inputs/update_read_groups.inputs))
# for sample in ${samples[@]}; do echo $sample;  qsub -v sample="$sample" ./Scripts/sam_flagstats.pbs ; sleep 2; done

#PBS -P <project>
#PBS -N stats
#PBS -l ncpus=14
#PBS -l mem=126GB
#PBS -l walltime=00:30:00
#PBS -q normalbw
#PBS -W umask=022
#PBS -l wd
#PBS -lstorage=<storage>

module load samtools/1.12

outdir=<outdir>
old_bam_dir=<old_bam_dir>
new_bam_dir=<new_bam_dir>


mkdir -p ${outdir}/old_stats
mkdir -p ${outdir}/new_stats


old_bam=${old_bam_dir}/${sample}.dedup.sort.realigned.bam # check file name format!
new_bam=${new_bam_dir}${sample}.final.bam

old_stats=${outdir}/old_stats/${sample}.flagstats
new_stats=${outdir}/new_stats/${sample}.flagstats


samtools flagstat -@ $PBS_NCPUS $old_bam > $old_stats

samtools flagstat -@ $PBS_NCPUS $new_bam > $new_stats

sdiff -s $old_stats $new_stats
